<TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="8dp"
                    android:text="@string/label_doctor"></TextView>
                <Spinner
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"></Spinner>
                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="8dp"
                    android:text="@string/label_schedule_date"></TextView>
                <EditText
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"></EditText>